name: Django CI

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8.5]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DEBUG: true
        SECRET_KEY: ${{ secrets.SECRET_KEY }}

        TEST_MONGO_URI: ${{ secrets.TEST_MONGO_URI }}
        TEST_MONGO_DB: ${{ secrets.TEST_MONGO_DB }}
        DATA_COLLECTION: ${{ secrets.DATA_COLLECTION }}
        USER_DATA_COLLECTION: ${{ secrets.USER_DATA_COLLECTION }}
        CONTACT_US_DATA_COLLECTION: ${{ secrets.CONTACT_US_DATA_COLLECTION }}

        TEST_AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
        TEST_AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
        TEST_AWS_STORAGE_BUCKET_NAME: ${{ secrets.TEST_AWS_STORAGE_BUCKET_NAME }}
        TEST_AWS_S3_OBJECT_URL_PREFIX: ${{ secrets.TEST_AWS_S3_OBJECT_URL_PREFIX }}
        TEST_BUCKET_SUBFOLDER: ${{ secrets.TEST_BUCKET_SUBFOLDER }}
      run: |
        cd server
        python manage.py test